name: Deploy via SSH a dabyd.com
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Obtener cÃ³digo desde GitHub
        uses: actions/checkout@v3

      - name: ðŸš€ Desplegar vÃ­a Rsync sobre SSH
        uses: Burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          # Carpeta local que estÃ¡s subiendo (ej: tu tema en el repo)
          path: ./ 
          # LA RUTA EXACTA EN TU SERVIDOR
          remote_path: /var/www/dabyd.com/html/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}